### ISSUE TITLE
作者训练的权重向量从docker拷贝出来上传到百度云，欢迎自取

### ISSUE THREAD

**Issue by 17723161064** [zhang0jhon/AttentionOCR#100]
链接：https://pan.baidu.com/s/1epliZqQ4ld4YEUlRNrIQ7g 
提取码：hees 
复制这段内容后打开百度网盘手机App，操作更方便哦--来自百度网盘超级会员V6的分享

**Comment by for1314ai** [comment]
### ICDAR_0.7.pb
链接：https://pan.baidu.com/s/1XWF9DPsMk0iR7EQzOXwd5w 
提取码：v4cs 
复制这段内容后打开百度网盘手机App，操作更方便哦--来自百度网盘超级会员V6的分享

**Comment by xycim** [comment]
感谢分享

**Comment by wenyu8020** [comment]
请问可以再上传一次吗 谢谢
作者的docker无法执行

**Comment by LebinLiang** [comment]
> ### ICDAR_0.7.pb
> 链接：https://pan.baidu.com/s/1XWF9DPsMk0iR7EQzOXwd5w 提取码：v4cs 复制这段内容后打开百度网盘手机App，操作更方便哦--来自百度网盘超级会员V6的分享

链接已经失效了可以再上传一遍吗？想要训练权重 344248024@qq.com，十分感谢
