### ISSUE TITLE
Default MaxPoolingOp only supports NHWC on device type CPU

### ISSUE THREAD

**Issue by Springzcf** [zhang0jhon/AttentionOCR#11]
你好：
请问我再运行完python flaskapp.py，上传图片之后，进行预测的时候，会显示下面的错误，请问这是什么原因导致的？
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU 
[[node pool0/MaxPool (defined at /tensor_flow/OCRSpace/ocr/ocr/text_detection.py:29) ]]

Original stack trace for 'pool0/MaxPool':

请问应该怎么修改呢？多谢。。。

**Comment by zhang0jhon** [comment]
docker环境 默认是在GPU环境下运行

**Comment by Springzcf** [comment]
感谢您的回复，那我需要改成CPU吗？尝试了一下可是报错还是一样的啊

**Comment by zhang0jhon** [comment]
目前还不支持CPU，需要NVIDIA GPU

**Comment by Springzcf** [comment]
我就是在NVIDIA GPU上运行的，好奇怪 = =|

**Comment by zhang0jhon** [comment]
错误信息显示应该是因为tensorflow没有使用GPU

**Comment by wyc2015fq** [comment]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU,我也遇到这个问题了，请问解决了吗？
