### ISSUE TITLE
docker运行demo时内存不够怎么配置

### ISSUE THREAD

**Issue by bigkun** [zhang0jhon/AttentionOCR#14]
`W tensorflow/core/common_runtime/bfc_allocator.cc:211] Allocator (GPU_0_bfc) ran out of memory trying to allocate 358.89MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
`

普通显卡
` tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: GeForce GT 1030 major: 6 minor: 1 memoryClockRate(GHz): 1.5185
pciBusID: 0000:01:00.0
totalMemory: 1.95GiB freeMemory: 1.63GiB
`

**Comment by zhang0jhon** [comment]
显存的大小不够，默认应该是需要4G以上的显卡，或者可以更改input图像的大小和sequence length
