### ISSUE TITLE
flag provided but not defined: --runtime

### ISSUE THREAD

**Issue by FortuneStar** [zhang0jhon/AttentionOCR#18]
这个错误是什么意思？完全没用过docker，难过。。。

**Comment by zhang0jhon** [comment]
应该是nvidia-docker的问题，具体安装过程请参考nvidia-docker提供的安装说明。。。

**Comment by FortuneStar** [comment]
多谢耐心解答，经过上网查找相关资料，已经可以跑起来了，多谢！！！
