### ISSUE TITLE
关于识别的问题

### ISSUE THREAD

**Issue by FortuneStar** [zhang0jhon/AttentionOCR#26]
假设已经定位到文字部分（暂不考虑定位方法），若采用AttentionOCR去识别，识别结果是针对图片中文字整体识别还是针对图片中的文字一个一个进行识别，因为之前采用crnn-ctc的模型是对图片中的文字一起识别，但是我看到您的images文件夹中图片有标识每一个汉字的识别概率，不知道我表达清楚没有^~^

**Comment by zhang0jhon** [comment]
是针对图像中的文字一起识别，只不过每个识别的文字都有识别的概率

**Comment by FortuneStar** [comment]
嗷嗷，谢谢！
