### ISSUE TITLE
作者您好，代码很优秀，请问训练好的文字检测模型会开源嘛？

### ISSUE THREAD

**Issue by Byronnar** [zhang0jhon/AttentionOCR#3]
类似这个，text_recognition_5435.pb

**Comment by zhang0jhon** [comment]
竞赛的模型文件在docker镜像里

**Comment by Byronnar** [comment]
好的看到啦，谢谢！

**Comment by kylechang523** [comment]
请问一下怎么从docker镜像获取模型文件呢？没有docker但是想测试一下效果呀

**Comment by 1456416403** [comment]
我已经从docker下载了 那个pb文件到本地了，可是在本地运行test.py的时候正确率非常非常低，请问是什么原因呢
