### ISSUE TITLE
关于训练的提问

### ISSUE THREAD

**Issue by FortuneStar** [zhang0jhon/AttentionOCR#31]
请问下您的AttentionOCR模型是单独训练的，还是和mask-rcnn结合在一起一起训练的？如果单独训练AttentionOCR模型，数据格式是FSNS-tfrecord吗？因为我准备用自己的数据训练，不去下载ICDAR官方数据。

**Comment by zhang0jhon** [comment]
模型是单独训练的，用来做文本行区域识别

**Comment by FortuneStar** [comment]
> 模型是单独训练的，用来做文本行区域识别

请问下文字识别部分，您的训练数据是什么格式的？
