### ISSUE TITLE
配置文件中model_name的值‘ocr’与‘ocr_with_normalized_bbox’有什么区别？如果训练样本是长文本，image_size需要改变吗，增大它的值，还需要修改其它配置吗，谢谢！

### ISSUE THREAD

**Issue by wuyunxiangwyx** [zhang0jhon/AttentionOCR#40]

**Comment by zhang0jhon** [comment]
'ocr_with_normalized_bbox'是我正在做的一个实验，与‘ocr’的区别主要是用来训练attention的时候使用padding后的图片还是原始mask后的图片，目前支持长度不超过32的长文本，如果是更长的文本行就需要增大image size以及sequence length。
