### ISSUE TITLE
长文本的效果忒儿差劲？这个怎么解决？

### ISSUE THREAD

**Issue by liuzhuang1024** [zhang0jhon/AttentionOCR#47]

**Comment by liuzhuang1024** [comment]
![image](https://user-images.githubusercontent.com/23006154/71556275-4bd2d200-2a71-11ea-8792-529e2d76cb0c.png)

**Comment by zhang0jhon** [comment]
竞赛数据集没有相似的文档长文本，需要用新的数据集重新训练。

**Comment by Wo-Ki** [comment]
我拿公开数据集(art+rects)训练430000次，用来识别车牌，效果也是不太好。前两个字还行，后面完全识别不到。这也是长文本的问题？

结果如下：
['皖', 'K'] [0.7606085  0.9683497  0.95730805]
['皖', 'K'] [0.7606051 0.9683497 0.9573083]
['啵', 'B'] [0.22663411 0.96232164 0.61064464]
['皖', 'G', '▪'] [0.4462814  0.99723685 0.8549502  0.9544695 ]
['皖', 'G', '▪'] [0.4462814  0.99723685 0.8549502  0.9544695 ]
['皖', 'A'] [0.8662637  0.84521544 0.9425101 ]
['啵', 'B'] [0.22663411 0.96232164 0.61064464]
['皖', 'A'] [0.8662637  0.84521544 0.9425101 ]

**Comment by zhang0jhon** [comment]
我把新的检测模型放到demo.sceneinception.com，可以先尝试一下效果

**Comment by Wo-Ki** [comment]
识别的效果还不错，能分享一下训练细节和数据吗？

**Comment by heromanba** [comment]
> 我把新的检测模型放到demo.sceneinception.com，可以先尝试一下效果

您好，感谢您分享这么好的工作，请问有可以finetune的权重吗？docker里的pb好像是不可以训练的？

**Comment by Wo-Ki** [comment]
能分享demo.sceneinception.com里的可以finetune的模型吗？非常感谢

**Comment by Nick198903** [comment]
> 我拿公开数据集(art+rects)训练430000次，用来识别车牌，效果也是不太好。前两个字还行，后面完全识别不到。这也是长文本的问题？
> 
> 结果如下： ['皖', 'K'] [0.7606085 0.9683497 0.95730805] ['皖', 'K'] [0.7606051 0.9683497 0.9573083] ['啵', 'B'] [0.22663411 0.96232164 0.61064464] ['皖', 'G', '▪'] [0.4462814 0.99723685 0.8549502 0.9544695 ] ['皖', 'G', '▪'] [0.4462814 0.99723685 0.8549502 0.9544695 ] ['皖', 'A'] [0.8662637 0.84521544 0.9425101 ] ['啵', 'B'] [0.22663411 0.96232164 0.61064464] ['皖', 'A'] [0.8662637 0.84521544 0.9425101 ]

你好 问下 这个概率是怎么回事呢 两个字符为什么有三个概率呢
