### ISSUE TITLE
可识别字符长度改为16

### ISSUE THREAD

**Issue by Bachelorwangwei** [zhang0jhon/AttentionOCR#50]
seq_len是单个文本行最多可识别的字符数，是这个意思吧。
我现在想训一个短文本行的模型，最长seq_len设置为16，请问还需要修改哪些地方？
直接改为16报错，报ValueRrror，维度不匹配, 具体错误为cannot feed value of shape(16,33) for Tensor 'label:0', which has shape(?,17)
麻烦您指点一下，多谢

**Comment by zhang0jhon** [comment]
数据预处理的seq_len也改成16了么？

**Comment by Bachelorwangwei** [comment]
恩恩，之前是预处理的时候没改，还是32，现在改成16好了，多谢了，很好的项目，手动点赞，哈哈
