### ISSUE TITLE
训练过程死锁，一直在waiting、

### ISSUE THREAD

**Issue by Bachelorwangwei** [zhang0jhon/AttentionOCR#51]

**Comment by Bachelorwangwei** [comment]
训练过程中，执行完train.py后，进程一直在等待状态，定位发现是tensorpack/input_source/input_source.py打完Pre-filling StagingArea日志，在执行stage.op.run(session=sess)的时候进入死锁，进程只占用一小部分显存，一直在等待中。

**Comment by Bachelorwangwei** [comment]
问题已解决，根据自己数据标签修改的dataset.py有问题，喂数据没喂到。

**Comment by qing3** [comment]
你好，我用自己数据的时候遇到了跟你一样的问题，请问你是哪里的数据标签有问题呀？

**Comment by mayidu** [comment]
请问一下，训练生成的模型是保存在哪儿了呢，checkpoint下没有看到保存的模型呢，有个.meta文件，是吗，保存的模型应该是个什么样的文件呢
