### ISSUE TITLE
请问训练出来的的模型包含了检测与识别吗？

### ISSUE THREAD

**Issue by Waynepoo** [zhang0jhon/AttentionOCR#52]
但是docker里面检测和识别是两个模型

**Comment by Bachelorwangwei** [comment]
训练出来的只是识别模型，检测还得用其他算法

**Comment by Waynepoo** [comment]
用自己训练的bp文件替换docker里面的bp文件，在docker运行里面运行报一下错误，怎么解决？
KeyError: "The name 'dropout:0' refers to a Tensor which does not exist. The operation, 'dropout', does not exist in the graph."

**Comment by Waynepoo** [comment]
> 训练出来的只是识别模型，检测还得用其他

**Comment by little2Rabbit** [comment]
@Waynepoo 请问你解决了吗，我也遇到这个问题
